apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx-svc
  labels:
    app: nginx
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.49.10
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
        resources: {}
status: {}
